# Pandas notes

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
#Data Frames are used to represent tables

df = pd.read_csv("filename.csv") # read the csv file and convert it into a data frame 
print(df)
#you can also create dataframe using python dictionaries
#e.g.
df = pd.DataFrame(dict_data)# keys will be columns and list of values will be the value

df.shape #-->shows the no. of rows, columns as a tuple
df.head(2)#prints first 2 rows
df.tail(1)
df[2:5] #--> prints row 2 to 5 (but not 5)

df.columns #prints the columns as a list
df.column_name #prints the column with column name as column_name

# the columns of a pandas DataFrame are of type Series
# e.g type(df['event']) --> pandas.core.series.Series

df[['event','day']] #-->prints the two columns as a data frame

#operations with a Data Frame:

df['temperature'].max()

df['temperature'].mean()

df['temperature'].std() #standard deviation

df.describe() #prints an entire table of all the statistics of the data in
# in the data frame

#Querying Data in a DataFrame
df[df.temperature>=32]
df[df.temperature = df.temperature.max()]

# NOTE: df.temperature and df['temperature'] both are the same

df[day][df.temperature = df.temperature.max()]
#prints only the day of max temp


df.index #returns RangeIndex

df.set_index('date', inplace = True) # makes the index as the date
#inplace boolean tells that you want df variable to be changed implicitly


df.loc('1/2/2017') #so now, the index is the date

df.reset_index(inplace = True)
# restores df to its original index i.e. 0 1 2..

In [ ]:
#DIFFERENT WAYS OF CREATING A DATA FRAME

df = read_csv("blahblah.csv")

df.read_excel("blahblah.xlsx")

df = pd.DataFrame(dictionary) # the way it was discussed above

df = pd.DataFrame(tuple_name)
#note: for tuples, the columns will have to be mentioned separately

#we can also use a list of dictionaries
df = pd.DataFrame(list_of_dictionaries)
#check the documentation for more

In [ ]:
#READING AND WRITING CSV, EXCEL FILES

df = pd.read_csv("stock_data.csv", skip_rows=3)#will skip first 3 row
#or another way,
df = pd.read_csv("data.csv", header=1) #will start from row 1(i.e 2nd row)

#what if you want to add header?
df = pd.read_csv("data.csv", header=None, names=['column1 name', 'col2name'])

df = pd.read_csv("stock_data.csv", nrows=3)#no. of rows you want to include in df

#how to handle n/a values?

df = pd.read_csv("stock_data.csv", na_values=['not available', 'n.a.', 'na', 'n/a'])


df = pd.read_csv("stock_data.csv", na_values={
    'col1':['na', 'not available'],
    'col2':['na', 'not available', -1]
}) #quite useful!

df.to_csv("new.csv")
#creates a new csv file in the directory of the program

df.to_csv('new.csv', index=false) #won't print the index

df.to_csv('new.csv', columns=['col1', 'col2'])

df.to_csv('new.csv', header= False) #skip the header in csv file.

 #reading excel files.
    
df = pd.read_excel("stock_data.xlsx", "Sheet1")

pd.to_excel("newfile.xlsx", sheet_name="stocks", index=False, startrow = 0, start col = 2)


#how to use converters:
 #first, we define a function,

def convert_people_cell(cell)
    if cell == 'na'
        return 'sam walton'
    return cell

df = pd.read_excel("stock_data.xlsx", "Sheet1", converters = {
    'people' : convert_people_cell
})

# the above will convert all the entries that are "na" in column 'people' to 'sam walton'

In [ ]:
#How to Handle Mising Data:

df = read_csv("weather_data.csv", parse_dates=['day'])
df.set_index('day', inplace = True)

new_df = df.fillna(0) #fills na data with 0
#for filling different contents in different columns, we do
new_df = df.fillna({
    'col1': 0,
    'col2': 1,
    'col3': 'Nope'
})

#to carry forward data of previous entry into next entry,
new_df = df.fillna(method ='ffill', limit=1) #forward fill
#limit 1 means u can copy only once
new_df = df.fillna(method ='bfill', axis = 'columns') #backward fill
#axis = columns : data will be copied from next column instead of row


new_df = df.interpolate() # takes average of front and back data entries

new_df = df.dropna(how="all") #drops rows with na entries

new_df = df.dropna(thresh=2) #drop only if threshold of na entries is exceeded

#Replace function

df.replace(-99999, np.NaN)
# if there are multiple values you want to replace at once, just use list or tuple!

df.replace((-9999, 8888), np.NaN)

#replace just specific columns as follows

new_df = df.replace({
    'temperature': -9999,
    'windspeed': 8888
}, np.NaN)

#if you wanna replace just a particular cell with some specific value...
new_df = df.replace({
    -9999: np.NaN,
    'No Event': 'Sunny'
})
#so here above, the -9999 wale entries will be replaced by NaN
# and the No Event entries will be replace by sunny

#how to replace a list of values with another list of values:
#this one is pretty important...

df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])
#so in the above function poor will be replaced with 1, av with 2 and so on..

In [ ]:
#GROUPING DATA AND SOME USEFUL ANALYSIS TOOLS

df = read_csv('weather_data.csv')
g = df.group_by('city')
#it will give a DataFrameGroupBy Object
#key-> group: value--> dataframe of data for that group

for city, city_df in g: #for key,value in dict
    print(city)
    print(city_df)
    
g.get_group('mumbai')

g.max() #returns a DataFrame i.e. you have combined the dataFrames
#gives max for each data frame

g.mean()
g.describe()
g.std()

%matplotlib inline
g.plot() # will give three separate plots for different groups

In [11]:
#CONCATENATION OF DATAFRAMES
import pandas as pd
india_weather = {
    'city': ['mumbai', 'delhi', 'bangalore'],
    'temperature':[32, 45, 30],
    'humidity': [80, 40, 78]
}
ind = pd.DataFrame(india_weather)


us_weather = {
    'city': ['new york', 'chicago', 'orlando'],
    'temperature':[22, 10, 30],
    'humidity': [21, 20, 78]
}

usa = pd.DataFrame(us_weather)

pd.concat([ind, usa], ignore_index=True) #ingnore_index will update indexes

df = pd.concat([ind, usa], keys=['india', 'us'])
#first data frame will have index 'india' and second one will have index 'us'
df.loc['india'] #--> to access one of the data Frame that you concatenated

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        40
2  bangalore           30        78